<a href="https://colab.research.google.com/github/OyeTimmy/Hamoye-Stage-C-/blob/main/Hamoye_Study_C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
import numpy as np
import pandas as pd
import csv
from bs4 import BeautifulSoup
import seaborn as sns
sns.set_style("darkgrid")
import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('fivethirtyeight')
import warnings
warnings.filterwarnings('ignore')

In [ ]:
UCI = pd.read_csv('https://raw.githubusercontent.com/OyeTimmy/Hamoye-Stage-C-/main/Data_for_UCI_named.csv')

In [ ]:
UCI.head()

tau1      tau2      tau3  ...        g4      stab     stabf
0  2.959060  3.079885  8.381025  ...  0.958034  0.055347  unstable
1  9.304097  4.902524  3.047541  ...  0.781760 -0.005957    stable
2  8.971707  8.848428  3.046479  ...  0.109853  0.003471  unstable
3  0.716415  7.669600  4.486641  ...  0.362718  0.028871  unstable
4  3.134112  7.608772  4.943759  ...  0.820923  0.049860  unstable

[5 rows x 14 columns]

In [ ]:
UCI.describe()

tau1          tau2  ...            g4          stab
count  10000.000000  10000.000000  ...  10000.000000  10000.000000
mean       5.250000      5.250001  ...      0.525000      0.015731
std        2.742548      2.742549  ...      0.274255      0.036919
min        0.500793      0.500141  ...      0.050028     -0.080760
25%        2.874892      2.875140  ...      0.287494     -0.015557
50%        5.250004      5.249981  ...      0.525002      0.017142
75%        7.624690      7.624893  ...      0.762433      0.044878
max        9.999469      9.999837  ...      0.999930      0.109403

[8 rows x 13 columns]

In [ ]:
UCI.info

<bound method DataFrame.info of           tau1      tau2      tau3  ...        g4      stab     stabf
0     2.959060  3.079885  8.381025  ...  0.958034  0.055347  unstable
1     9.304097  4.902524  3.047541  ...  0.781760 -0.005957    stable
2     8.971707  8.848428  3.046479  ...  0.109853  0.003471  unstable
3     0.716415  7.669600  4.486641  ...  0.362718  0.028871  unstable
4     3.134112  7.608772  4.943759  ...  0.820923  0.049860  unstable
...        ...       ...       ...  ...       ...       ...       ...
9995  2.930406  9.487627  2.376523  ...  0.608385  0.023892  unstable
9996  3.392299  1.274827  2.954947  ...  0.366120 -0.025803    stable
9997  2.364034  2.842030  8.776391  ...  0.145984 -0.031810    stable
9998  9.631511  3.994398  2.757071  ...  0.818391  0.037789  unstable
9999  6.530527  6.781790  4.349695  ...  0.942631  0.045263  unstable

[10000 rows x 14 columns]>

In [ ]:
print(UCI.duplicated().sum())
print(UCI.isnull().sum())

0
tau1     0
tau2     0
tau3     0
tau4     0
p1       0
p2       0
p3       0
p4       0
g1       0
g2       0
g3       0
g4       0
stab     0
stabf    0
dtype: int64


In [ ]:
UCI.dtypes

tau1     float64
tau2     float64
tau3     float64
tau4     float64
p1       float64
p2       float64
p3       float64
p4       float64
g1       float64
g2       float64
g3       float64
g4       float64
stab     float64
stabf     object
dtype: object

In [ ]:
UCI.drop(['stab'], axis=1, inplace=True)

In [ ]:
UCI.head()

tau1      tau2      tau3  ...        g3        g4     stabf
0  2.959060  3.079885  8.381025  ...  0.887445  0.958034  unstable
1  9.304097  4.902524  3.047541  ...  0.562139  0.781760    stable
2  8.971707  8.848428  3.046479  ...  0.839444  0.109853  unstable
3  0.716415  7.669600  4.486641  ...  0.929381  0.362718  unstable
4  3.134112  7.608772  4.943759  ...  0.656947  0.820923  unstable

[5 rows x 13 columns]

In [ ]:
x = UCI.drop(columns = 'stabf')
y = UCI['stabf']

In [ ]:
# Spliting into test and train data
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=1)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [ ]:
scaled_train = scaler.fit_transform(x_train)
scaled_train = pd.DataFrame(scaled_train)
scaled_train

0         1         2   ...        9         10        11
0     0.367327 -0.986042  0.650447  ...  0.339859  0.585568  0.492239
1    -0.064659  0.089437  1.035079  ... -1.558488  1.429649 -1.443521
2    -1.467850  1.298418 -0.502536  ...  1.451534 -1.045743  0.492489
3     0.820081  0.529920  1.299657  ...  1.361958  1.604140  0.275303
4     0.665424 -1.425627  0.312300  ...  0.695660  1.137504 -1.312575
...        ...       ...       ...  ...       ...       ...       ...
7995  1.551314  0.007408 -1.177640  ...  0.313976 -1.625728 -0.637401
7996  1.015925 -0.223483 -1.489381  ... -0.755209  0.734821 -0.304433
7997  0.657609 -0.722756 -1.405888  ...  0.293100 -1.550587  0.810344
7998 -0.059316 -1.260532 -1.010471  ... -0.388255 -0.726781  1.667916
7999 -1.473214  0.638438  0.250122  ... -1.174110  1.179282  0.783627

[8000 rows x 12 columns]

In [ ]:
scaled_test = scaler.fit_transform(x_test)
scaled_test = pd.DataFrame(scaled_test)
scaled_test

0         1         2   ...        9         10        11
0     0.592163 -0.420565  1.472472  ...  1.175287 -1.492644  1.086291
1     0.199183  0.364543 -0.190076  ... -0.395949  1.412703  1.227535
2    -1.086035 -0.321834 -0.873505  ... -1.444370  0.654216 -1.679799
3    -0.087014 -1.113357  0.361518  ... -1.679450 -0.349573  1.057439
4     0.873004  1.425833  0.080476  ... -1.475773  0.957057 -0.817608
...        ...       ...       ...  ...       ...       ...       ...
1995  1.119526 -0.682371 -1.362900  ... -0.114316 -1.251379 -1.280864
1996 -1.084900 -0.815496  1.010385  ...  0.899379 -1.050349 -1.091915
1997  0.947138 -1.668313 -1.629077  ...  0.128899  0.576286  1.320848
1998 -1.127354  0.184573 -0.238207  ...  0.800172 -1.348463 -0.799858
1999 -1.385560  1.499043  0.272971  ... -0.920581  0.009039  1.190559

[2000 rows x 12 columns]

In [ ]:
# Random Trees Classifer

from sklearn.ensemble import RandomForestClassifier
Rand = RandomForestClassifier(random_state = 1)
Rand.fit(scaled_train, y_train)
predict_y = Rand.predict(scaled_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [ ]:
def score_data(y_test, predict_y):
    print('Accuracy : {}'. format(accuracy_score(y_true = y_test, y_pred = predict_y)))
    print('\n Confusion Matrix \n', confusion_matrix(y_true = y_test, y_pred = predict_y))
    print('\n Classification Report \n', classification_report(y_true = y_test,y_pred = predict_y))

In [ ]:
score_data(y_test, predict_y)

Accuracy : 0.928

 Confusion Matrix 
 [[ 624   88]
 [  56 1232]]

 Classification Report 
               precision    recall  f1-score   support

      stable       0.92      0.88      0.90       712
    unstable       0.93      0.96      0.94      1288

    accuracy                           0.93      2000
   macro avg       0.93      0.92      0.92      2000
weighted avg       0.93      0.93      0.93      2000



In [ ]:
# Extra Trees Classifier

from sklearn.ensemble import ExtraTreesClassifier
TreeClass =ExtraTreesClassifier()
TreeClass.fit(scaled_train, y_train)
predict_y = TreeClass.predict(scaled_test)
score_data(y_test, predict_y)

Accuracy : 0.927

 Confusion Matrix 
 [[ 599  113]
 [  33 1255]]

 Classification Report 
               precision    recall  f1-score   support

      stable       0.95      0.84      0.89       712
    unstable       0.92      0.97      0.95      1288

    accuracy                           0.93      2000
   macro avg       0.93      0.91      0.92      2000
weighted avg       0.93      0.93      0.93      2000



In [ ]:
# Extra tree classifier and Randomized CSV

n_estimators = [50, 100, 300, 500, 1000]
min_samples_split = [2, 3, 5, 7, 9]
min_samples_leaf = [1, 2, 4, 6, 8]
max_features = ['auto', 'sqrt', 'log2', None]

hyperparameter_grid = {'n_estimators' : n_estimators,
                       'min_samples_leaf' : min_samples_leaf,
                       'min_samples_split' : min_samples_split,
                       'max_features' : max_features}

In [ ]:
from sklearn.model_selection import RandomizedSearchCV
TreeClass = ExtraTreesClassifier()

Random = RandomizedSearchCV(estimator=TreeClass, param_distributions = hyperparameter_grid, cv=5, n_iter=10, n_jobs=-1, verbose=1, random_state=1, scoring='accuracy')
Random.fit(scaled_train, y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  46 tasks      | elapsed:  1.4min
[Parallel(n_jobs=-1)]: Done  50 out of  50 | elapsed:  1.5min finished


RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=ExtraTreesClassifier(bootstrap=False,
                                                  ccp_alpha=0.0,
                                                  class_weight=None,
                                                  criterion='gini',
                                                  max_depth=None,
                                                  max_features='auto',
                                                  max_leaf_nodes=None,
                                                  max_samples=None,
                                                  min_impurity_decrease=0.0,
                                                  min_impurity_split=None,
                                                  min_samples_leaf=1,
                                                  min_samples_split=2,
                                                  min_weight_fraction_leaf=0.0,
                                        

In [ ]:
predict_y = Random.predict(scaled_test)
score_data(y_test, predict_y)

Accuracy : 0.9245

 Confusion Matrix 
 [[ 615   97]
 [  54 1234]]

 Classification Report 
               precision    recall  f1-score   support

      stable       0.92      0.86      0.89       712
    unstable       0.93      0.96      0.94      1288

    accuracy                           0.92      2000
   macro avg       0.92      0.91      0.92      2000
weighted avg       0.92      0.92      0.92      2000



In [ ]:
# XGBoost
import xgboost as xgb

In [ ]:
from xgboost import XGBClassifier
Boost = XGBClassifier()
Boost.fit(scaled_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [ ]:
predict_y = Boost.predict(scaled_test)
score_data(y_test, predict_y)

Accuracy : 0.919

 Confusion Matrix 
 [[ 599  113]
 [  49 1239]]

 Classification Report 
               precision    recall  f1-score   support

      stable       0.92      0.84      0.88       712
    unstable       0.92      0.96      0.94      1288

    accuracy                           0.92      2000
   macro avg       0.92      0.90      0.91      2000
weighted avg       0.92      0.92      0.92      2000



In [ ]:
from lightgbm import LGBMClassifier

In [ ]:

Lg = LGBMClassifier()
Lg.fit(scaled_train,y_train)
predict_y=Lg.predict(scaled_test)

In [ ]:
score_data(y_test, predict_y)

Accuracy : 0.9355

 Confusion Matrix 
 [[ 635   77]
 [  52 1236]]

 Classification Report 
               precision    recall  f1-score   support

      stable       0.92      0.89      0.91       712
    unstable       0.94      0.96      0.95      1288

    accuracy                           0.94      2000
   macro avg       0.93      0.93      0.93      2000
weighted avg       0.94      0.94      0.94      2000

